# 利用Python机器学习

## 数据导入和可视化

In [1]:
# 数据包含鸢尾花（iris）数据集，这是一个包含了三种鸢尾花（山鸢尾、维吉尼亚鸢尾和变色鸢尾）的各50个数据样本的多元数据集，每个样本都有四个特征（或者说变量），即花萼（sepal）和花瓣（petal）的长度和宽度。以厘米为单位。

import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

iris_X = iris.data
iris_y = iris.target

np.unique(iris_y)
iris_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
# Split iris data in train and test data
# A random permutation, to split the data randomlynp.random.seed(0)
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

#print iris_X
indices = np.random.permutation(len(iris_X))  #permutation(x) 返回一个随机排列
print indices
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

[118  37  40  46 141  16  97  67  13  18 126  35  34  38 135  12 117  83
  27  51  85  74   6  23  71  98 104 103  41  39  36 137 108  52 138  78
 146 105  99 125  89  95  94  44   8  77  69  17  48  73   5  65  90  93
 136  22 147  63  92 109 119  20 111  11 113 114  29  10  96 148  31   0
 123 130 128  58 124  32  19  45  91  66   4  62   9  87 106  55  28  86
 120  30 115 112 139  68  50  33  61 144 101   3   7 140  81 121  84  15
  54  26 102  43  88 145  75 132  25 133 142 127 116 131  47  72  14 149
  76  64 129 134  56  49 107  70  42 122 100  21  80  57   2  53  24  82
   1 110  59  79 143  60]


In [3]:
#糖尿病数据集包含442个患者的10个生理特征（年龄，性别、体重、血压）和一年以后疾病级数指标。

diabetes = datasets.load_diabetes()

diabetes_X_train = diabetes.data[:-20]
diabetes_X_test = diabetes.data[-20:]

diabetes_y_train = diabetes.target[:-20]
diabetes_y_test = diabetes.target[-20:]

print type(diabetes_X_train)
print diabetes_X_train.shape

print diabetes_X_train

<type 'numpy.ndarray'>
(422L, 10L)
[[ 0.03807591  0.05068012  0.06169621 ..., -0.00259226  0.01990842
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ..., -0.03949338 -0.06832974
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ..., -0.00259226  0.00286377
  -0.02593034]
 ..., 
 [-0.02004471 -0.04464164 -0.0547075  ..., -0.03949338 -0.07408887
  -0.0052198 ]
 [ 0.02354575 -0.04464164 -0.03638469 ...,  0.03430886 -0.03324879
   0.06105391]
 [ 0.03807591  0.05068012  0.0164281  ...,  0.07120998  0.04976866
   0.01549073]]


## 预测集和测试集 cross_validation.train_test_split

In [5]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
data= iris.data
target= iris.target

from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, target,test_size=0.4, random_state=0)

data

C:\Users\yuli\AppData\Local\Continuum\Anaconda3\envs\Python27\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4


train_test_split是交叉验证中常用的函数，功能是从样本中随机的按比例选取train data和testdata，形式为：

X_train,X_test, y_train, y_test =

cross_validation.train_test_split(train_data,train_target,test_size=0.4, random_state=0)
•参数解释：

train_data：所要划分的样本特征集

train_target：所要划分的样本结果

test_size：样本占比，如果是整数的话就是样本的数量

random_state：是随机数的种子。

随机数种子：其实就是该组随机数的编号，在需要重复试验的时候，保证得到一组一样的随机数。比如你每次都填1，其他参数一样的情况下你得到的随机数组是一样的。但填0或不填，每次都会不一样。

随机数的产生取决于种子，随机数和种子之间的关系遵从以下两个规则：

种子不同，产生不同的随机数；种子相同，即使实例不同也产生相同的随机数。


In [14]:
## 下面使用的数据集

In [5]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
data= iris.data
target= iris.target
print data
print target
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, target,test_size=0.4, random_state=0)


[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

## 贝叶斯分类

In [8]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(train,t_train) # train

expected = t_test
predicted = model.predict(test)  ###

print (model.predict(test))

print (model.score(test,t_test)) # test

print (model.score(train,t_train)) # test
#0.93333333333333335

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 2 1 1 2 1 2]
0.933333333333
0.977777777778
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.85      1.00      0.92        23
          2       1.00      0.81      0.89        21

avg / total       0.94      0.93      0.93        60

[[16  0  0]
 [ 0 23  0]
 [ 0  4 17]]


## 线性回归

In [15]:
from sklearn import linear_model

regr = linear_model.LinearRegression()  ########

regr.fit(diabetes_X_train, diabetes_y_train)

print(regr.coef_)

predictions={}
predictions['intercept'] = regr.intercept_
predictions['coefficient'] = regr.coef_

print predictions

# The mean square error
np.mean((regr.predict(diabetes_X_test)-diabetes_y_test)**2)
# Explained variance score: 1 is perfect prediction# and 0 means that there is no linear relationsh

[  3.03499549e-01  -2.37639315e+02   5.10530605e+02   3.27736980e+02
  -8.14131709e+02   4.92814588e+02   1.02848452e+02   1.84606489e+02
   7.43519617e+02   7.60951722e+01]
{'coefficient': array([  3.03499549e-01,  -2.37639315e+02,   5.10530605e+02,
         3.27736980e+02,  -8.14131709e+02,   4.92814588e+02,
         1.02848452e+02,   1.84606489e+02,   7.43519617e+02,
         7.60951722e+01]), 'intercept': 152.76430691633442}


2004.5676026898211

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x,y)

print (model.coef_)
predictions={}
predictions['intercept'] = model.intercept_
predictions['coefficient'] = model.coef_

print (predictions)

# The mean square error
np.mean((model.predict(x)-y)**2)


from sklearn.metrics import mean_squared_error

print mean_squared_error(model.predict(x),y)

## Logistic回归

In [16]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(train,t_train)

expected = t_test
predicted = model.predict(test)  ###

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.78      0.88        23
          2       0.81      1.00      0.89        21

avg / total       0.93      0.92      0.92        60

[[16  0  0]
 [ 0 18  5]
 [ 0  0 21]]


## K近邻

In [60]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier  ####

# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier() ####

model.fit(train,t_train)

expected = t_test
predicted = model.predict(test)  ###

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       0.92      0.96      0.94        23
  virginica       0.95      0.90      0.93        21

avg / total       0.95      0.95      0.95        60

[[16  0  0]
 [ 0 22  1]
 [ 0  2 19]]


In [ ]:
from sklearn import datasets, neighbors, linear_model
digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target
n_samples = len(X_digits)

train_n=int(0.9 * n_samples)
X_train = X_digits[:train_n]
y_train = y_digits[:train_n]
X_test = X_digits[train_n:]
y_test = y_digits[train_n:]
print ('X_train: \n', X_train)
print ('y_train:  \n ', y_train)


knn = neighbors.KNeighborsClassifier()
print('KNN score: %f' % knn.fit(X_train, y_train).score(X_test, y_test))

logistic = linear_model.LogisticRegression()
print('LogisticRegression score: %f' % logistic.fit(X_train, y_train).score(X_test, y_test))

## 决策树

In [17]:
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier   ####

model = DecisionTreeClassifier()   ####

print model

model.fit(train,t_train)

expected = t_test
predicted = model.predict(test)  ###

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.92      0.96      0.94        23
          2       0.95      0.90      0.93        21

avg / total       0.95      0.95      0.95        60

[[16  0  0]
 [ 0 22  1]
 [ 0  2 19]]


## 支持向量机

In [2]:
from sklearn import metrics
from sklearn.svm import SVC   ####

model = SVC()   ####
model.fit(train,t_train)

print model

model.fit(train,t_train)

expected = t_test
predicted = model.predict(test)  ###

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.92      0.96      0.94        23
          2       0.95      0.90      0.93        21

avg / total       0.95      0.95      0.95        60

[[16  0  0]
 [ 0 22  1]
 [ 0  2 19]]


In [13]:
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]


from sklearn import svm

svc = svm.SVC(kernel='linear') #kernel='rbf'
svc.fit(iris_X_train, iris_y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## 聚类

In [21]:
from sklearn import cluster, datasets
iris = datasets.load_iris()
X_iris = iris.data
y_iris = iris.target
k_means = cluster.KMeans(n_clusters=3)
k_means.fit(X_iris) 

print(k_means.labels_[::10])
print(y_iris[::10])

print (y_iris)

[1 1 1 1 1 2 2 2 2 2 0 0 0 0 0]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## 神经网络

如何用Python和SciKit Learn 0.18实现神经网络【***】

GitHub 链接：https://github.com/Rogerh91/Springboard-Blog-Tutorials/blob/master/Neural%20Networks%20/JMPortilla_SpringBoard_Blog_Neural_Network.ipynb

### 数据

本文的分析主题为葡萄酒。葡萄酒伪劣品是一件非常现实的事情，让我们来看看 Python 的神经网络是否可以帮助解决这个问题。我们将使用 UCI 机器学习库中的葡萄酒数据集。它具有不同葡萄酒的各种化学特征，均在意大利同一地区生长，但数据标签分类为三种不同的品种。我们将尝试建立一个可以根据其化学特征对葡萄酒品种进行分类的神经网络模型。

数据集链接：https://archive.ics.uci.edu/ml/datasets/Wine


In [5]:
import pandas as pd
wine = pd.read_csv('wine_data.csv', names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])


In [6]:
wine.head()

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [7]:
wine.describe().transpose()

count        mean         std     min       25%  \
Cultivator            178.0    1.938202    0.775035    1.00    1.0000   
Alchol                178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity_of_Ash     178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_phenols         178.0    2.295112    0.625851    0.98    1.7425   
Falvanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Cultivator              2.000    3.0000     3.00  
Alchol                 13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Alcalinity_of_Ash      19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_phenols           2.355    2.8000     3.88  
Falvanoids              2.135    2.8750     5.08  
Nonflavanoid_phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [8]:
# 178 data points with 13 features and 1 label column
wine.shape
 

(178, 14)

### 准备训练集和测试集

In [9]:
X = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

### 数据预处理

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
#StandardScaler(copy=True, with_mean=True, with_std=True)

X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)


In [11]:
# 使用sklearn.preprocessing.StandardScaler类，使用该类的好处在于可以保存训练集中的参数（均值、方差）直接使用其对象转换测试集数据。

### 训练模型

现在我们来训练模型。SciKit-learn 使用 estimator（估计量）对象。我们将从 SciKit-Learn 的 neural_network 库导入我们的估计量（多层感知器分类器模型/MLP）。

In [12]:
from sklearn.neural_network import MLPClassifier

接下来我们创建一个模型的实例，可以自定义很多参数，我们将只定义 hidden_layer_sizes 参数。此参数传入的是一个元组，表示计划在每个层的神经元数量，其中元组中的第 n 个元素表示 MLP 模型第 n 层中的神经元数量。有很多参数可供选择，但是为了简单起见，我们将选择具有相同数量神经元的 3 层神经网络，每层的神经元数量与数据的特征数相同（13），并将最大迭代次数设置为 500 次。

In [13]:
mlp = MLPClassifier(hidden_layer_sizes=(5,4,3),max_iter=500)

In [14]:
print X_train[0]
print type(y_train) #Serries

mlp.fit(X_train,y_train)

[-1.71154722 -0.83293567  1.22720537  0.14464654 -0.37953804  0.755904
  0.93287277 -0.61872602  1.66148197 -1.00367782  0.01853102  0.99370121
 -0.20758636]
<class 'pandas.core.series.Series'>


C:\Users\yuli\AppData\Local\Continuum\Anaconda3\envs\Python27\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 4, 3), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [36]:
predictions = mlp.predict(X_test)

In [37]:
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,predictions))


[[12  1  0]
 [ 1 21  1]
 [ 0  0  9]]


In [38]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          1       0.92      0.92      0.92        13
          2       0.95      0.91      0.93        23
          3       0.90      1.00      0.95         9

avg / total       0.93      0.93      0.93        45



结果不错！看来测试集中我们只错误分类了 1 瓶葡萄酒！考虑到我们的 Python 神经网络的代码行很少，这个效果是非常好的。然而，多层感知器模型的缺点在于解释模型本身。例如，模型的权重和偏差与数据特征的关系以及哪些特征最重要将不容易解释。

如果想查看 MLP 训练模型得到的权重和偏差，使用 public 属性 coefs_ 和 intercepts_。

coefs_ 是权重矩阵的列表，其中索引 i 处的权重矩阵表示层 i 和层 i+1 之间的权重。

intercepts_ 是偏差向量的列表，其中索引 i 处的向量表示添加到层 i+1 的偏差值。


In [39]:
print mlp.coefs_

[array([[ 0.3334656 ,  0.1963113 , -0.78004223, -0.69121645, -0.00162402],
       [ 0.7181468 , -0.03145861,  0.4238024 ,  0.03938195,  0.37708547],
       [-0.18276947,  0.16225809,  0.24203913, -0.79769423, -0.09741635],
       [-0.68884032, -0.05278225,  0.27609942,  0.15868726,  0.14975873],
       [-0.01138432, -0.22881671, -0.47807436, -0.27305632,  0.3662932 ],
       [ 0.30733055, -0.46757901, -0.62469162,  0.26954857,  0.12050697],
       [ 1.00843851, -1.00401997,  0.04708207, -0.26119794, -0.45885907],
       [-0.00172866, -0.06066618,  0.22152568,  0.15294015,  0.13023803],
       [-0.32215151, -0.45139988,  0.36678091,  0.13726917, -0.29302762],
       [ 0.43648999,  0.97786165, -0.41163859, -0.67470876,  0.11215247],
       [ 0.60453288,  0.11314865,  0.13186717,  0.70532563, -0.56590094],
       [ 1.04598987, -0.75187977, -0.791392  ,  0.65833259, -0.40989129],
       [ 0.79301039, -0.53388075, -0.19475807,  0.01378644,  0.09423425]]), array([[-0.34629169, -0.32788773,  

In [40]:
print mlp.coefs_[0]

[[ 0.3334656   0.1963113  -0.78004223 -0.69121645 -0.00162402]
 [ 0.7181468  -0.03145861  0.4238024   0.03938195  0.37708547]
 [-0.18276947  0.16225809  0.24203913 -0.79769423 -0.09741635]
 [-0.68884032 -0.05278225  0.27609942  0.15868726  0.14975873]
 [-0.01138432 -0.22881671 -0.47807436 -0.27305632  0.3662932 ]
 [ 0.30733055 -0.46757901 -0.62469162  0.26954857  0.12050697]
 [ 1.00843851 -1.00401997  0.04708207 -0.26119794 -0.45885907]
 [-0.00172866 -0.06066618  0.22152568  0.15294015  0.13023803]
 [-0.32215151 -0.45139988  0.36678091  0.13726917 -0.29302762]
 [ 0.43648999  0.97786165 -0.41163859 -0.67470876  0.11215247]
 [ 0.60453288  0.11314865  0.13186717  0.70532563 -0.56590094]
 [ 1.04598987 -0.75187977 -0.791392    0.65833259 -0.40989129]
 [ 0.79301039 -0.53388075 -0.19475807  0.01378644  0.09423425]]


In [41]:
print mlp.coefs_[1]

[[-0.34629169 -0.32788773  1.20824451 -0.55023072]
 [ 0.5770083   0.55896471 -0.21731978  0.82345355]
 [ 1.16984048  0.0383347   0.2019638   0.46220823]
 [ 1.25812275 -0.42275916 -0.70899322 -0.73752058]
 [-0.1173686  -0.19348006 -0.58655318  0.67908274]]


In [42]:
print mlp.coefs_[2]

[[ 0.34596632  0.64662483  1.22372704]
 [-0.30425113 -0.02589355  0.05331896]
 [ 0.41847678 -0.25872919 -0.38249423]
 [-0.30262958 -0.70093946  0.3301845 ]]


In [43]:
print mlp.coefs_[3]

[[ 1.24757866  0.09431943 -1.35807452]
 [-0.76183213  0.26787287 -1.20908575]
 [-0.88523765  0.3185924   0.7451357 ]]


In [44]:
print mlp.intercepts_[0]

[ 0.41274066  0.35195916  0.84022064  0.17062269 -0.65291046]
